[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
